/** Stable names for Host-provided resources. Platform names identify icons, not mandatory providers. */
export const HOST_ICON_NAMES = [
  'platform.tx',
  'platform.kg',
  'platform.kw',
  'platform.wy',
  'platform.mg',
  'platform.local',
  'platform.all',
  'search',
  'music-note',
  'library',
  'cloud',
  'server',
  'import',
  'chart',
  'settings',
  'play',
  'pause',
  'download',
  'share',
  'account',
  'heart',
  'refresh',
  'close',
  'add',
  'info',
] as const
export type HostIconName = (typeof HOST_ICON_NAMES)[number]
export const HOST_ASSET_NAMES = ['app.logo', 'placeholder.cover', 'placeholder.avatar'] as const
export type HostAssetName = (typeof HOST_ASSET_NAMES)[number]
export const PERMISSION_NAMES = [
  'network.request',
  'network.private',
  'network.discovery',
  'credentials.use',
  'credentials.read',
  'library.read',
  'library.write',
  'library.delete',
  'player.read',
  'player.control',
  'playback.fallback.hold',
  'files.read',
  'files.write',
  'downloads.create',
  'clipboard.read',
  'clipboard.write',
  'notifications.system',
  'external.open',
  'background.run',
  'services.consume',
  'sharing.publish',
  'sharing.revoke',
  'guests.manage',
  'guests.run',
] as const
export type PermissionName = (typeof PERMISSION_NAMES)[number]
export const LODASH_METHODS = [
  'chunk',
  'compact',
  'concat',
  'difference',
  'drop',
  'dropRight',
  'flatten',
  'flattenDeep',
  'head',
  'last',
  'intersection',
  'uniq',
  'uniqBy',
  'union',
  'zip',
  'take',
  'takeRight',
  'groupBy',
  'keyBy',
  'countBy',
  'orderBy',
  'sortBy',
  'partition',
  'shuffle',
  'sample',
  'map',
  'filter',
  'find',
  'some',
  'every',
  'reduce',
  'includes',
  'get',
  'has',
  'pick',
  'omit',
  'mapKeys',
  'mapValues',
  'cloneDeep',
  'isEqual',
  'isEmpty',
  'isNil',
  'isString',
  'isNumber',
  'isArray',
  'isPlainObject',
  'camelCase',
  'kebabCase',
  'snakeCase',
  'startCase',
  'capitalize',
  'escape',
  'unescape',
  'trim',
  'truncate',
  'debounce',
  'throttle',
  'once',
  'memoize',
  'clamp',
  'range',
  'sum',
  'sumBy',
  'round',
] as const
/** 引用宿主图标；例如 hostIcon('platform.tx')，不内嵌图片。 */
export function hostIcon(name: HostIconName): { kind: 'host'; name: HostIconName } {
  return { kind: 'host', name }
}
